train: "/home/manojkumargalla/ResUNet/data/train"
valid: "/blue/pinaki.sarder/manojkumargalla/PostProcess/data/WSI_tiles/"
# valid: "/home/manojkumargalla/ResUNet/tbm_mini_dataset/test/"
# pred: "/home/manojkumargalla/ResUNet/tbm_mini_dataset/test/predicted_mask_crop/"
pred: "/blue/pinaki.sarder/manojkumargalla/PostProcess/data/WSI_tiles_predictions/"

log: "logs"
logging_step: 10
validation_interval: 100 # Save and valid have same interval
checkpoints: "/home/manojkumargalla/PostProcess/models/ResUnetTrain5_checkpoint_1000.pt"

batch_size: 16
lr: 0.001
RESNET_PLUS_PLUS: True
IMAGE_SIZE: 512
CROP_SIZE: 512